#!/usr/bin/env bash
#
# This requires git and virtualenv
#

install_deps ()
{
  revealjs && ace && staticjinja
}

GIT="git clone --depth=1"

# To display a slideshow
revealjs ()
{
  local dir=reveal
  [ -d $dir ] || $GIT https://github.com/hakimel/reveal.js.git $dir
  # return $? # This is implied.
}

# For intelligent code highlighting + editing
# (revealjs has builtin code highlighting + editing capability, but it's
#   comparatively pretty weak. If you're going to have editing, might as
#   well do it correctly)
ace ()
{
  local dir=ace
  [ -d $dir ] || $GIT https://github.com/ajaxorg/ace-builds.git $dir
}

# To combine slides
staticjinja ()
{
  mkdir venv
  virtualenv venv && . venv/bin/activate && pip install staticjinja
}

install_deps


# Only need the last commit, since in this case I'm not actually using git
#   for version control


